name: Build and publish

on: 
  push:
    branches:
    - "main"

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo

    - name: Build and publish "head" Docker image
      uses: ericoporto/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.MY_SECRET }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: containedpywine # Provide Docker image name
        image-tag: latest # Provide Docker image tag
